### PR TITLE
Partitioning, NOD_INF.OUT and other handy tools

### PR DESCRIPTION
**Pull request by martinvonk**
Here you can find most of the functions that I created for pHydrus during my MSc Thesis.

### CODE REVIEW

**Comment by raoulcollenteur** [comment]
Hi @martinvonk ,

Please check the code for PEP8 (especially line length) and rewrite the docstrings to apply Numpy doc format. Have a look at the other docstrings in pHydrus for examples.

Also, I think you have a method "create_nonlinear_profile", could you add that too to this PR?

I'll have another look later this week.
Thanks,
Raoul

**Comment by mvremec** [comment]
Hi @martinvonk,

and thanks for the commits! 
I am thinking whether it would be better if you would contribute the partitioning function to PyEt (I would then also add the Beers law for partitioning).
In this way, we would separate the Evaporation part in PyEt from the soil water fluxes modelling in Phydrus.

What do you think @raoulcollenteur , @martinvonk?

Best,
Matevz

**Comment by martinvonk** [comment]
@raoulcollenteur I'll have a look next week. My create_nonlinear_profile function is a bit wonky but I'll add it as well. 

@mvremec I do agree that the partitioning function would be useful in PyEt. However, one could also make an argument for adding it to pHydrus since the partitioning is already present in the HYDRUS-1D executable. Partitioning the evaporation fluxes in pHydrus and writing them to ATMOSPH.IN is much more clear imo.

**Comment by martinvonk** [comment]
Closing this PR because I have a new pull request with all changes: #61 . Maybe we can all have a look this week ;p

**Pull request closed without merging**
